// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;


public class DefaultSuiteTest {

  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
    driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(7));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void authorization() {
    driver.get("https://otvet.mail.ru/");
    driver.manage().window().setSize(new Dimension(1050, 716));
    {
      WebElement element = driver.findElement(By.linkText("Регистрация"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ph-login"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".ph-login")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().frame(0);
    driver.findElement(By.name("username")).sendKeys("test_sftware_lab3");
    driver.findElement(By.cssSelector(".primary-0-2-93 > .innerTextWrapper-0-2-82:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".focus-0-2-61 .input-0-2-71")).click();
    driver.findElement(By.cssSelector(".focus-0-2-61 .input-0-2-71")).sendKeys("7");
    driver.findElement(By.cssSelector(".focus-0-2-61 .input-0-2-71")).sendKeys("9");
    driver.findElement(By.cssSelector(".vkuiTypography")).sendKeys("86132538");
    driver.findElement(By.cssSelector(".inner-0-2-81")).click();
  }

  @Test
  public void chooseQuestion() {
    driver.get("https://otvet.mail.ru/?app_id_mytracker=52867&from=navi&authid=m85xg331.pu&reset_soft_vkid_bind=1&dwhsplit=s10273.b1s");
    driver.manage().window().setSize(new Dimension(1050, 716));
    driver.findElement(By.linkText("Ноут выключается после запуска.")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".X5s96 > .Wjnkw")).click();
    driver.findElement(By.cssSelector(".NaroV:nth-child(2) > .Wjnkw")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ProseMirror"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Лучше всего обратитесь к специалистам</p>'}", element);
    }
    driver.findElement(By.cssSelector(".VBdLL > .Wjnkw")).click();
    driver.findElement(By.cssSelector(".cxc3c:nth-child(3) .T868K > .q5y_1 > .Wjnkw")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ProseMirror"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Хорошая идея</p>'}", element);
    }
    driver.findElement(By.cssSelector(".WOCVm > .Wjnkw")).click();
    driver.close();
  }

  @Test
  public void createPoll() {
    driver.get("https://otvet.mail.ru/");
    driver.manage().window().setSize(new Dimension(1050, 716));
    driver.findElement(By.cssSelector(".Im7BZ > .Wjnkw")).click();
    driver.findElement(By.id("question_text")).sendKeys("Какой фреймворк лучший для начала изучения");
    driver.findElement(By.id("question_text")).sendKeys("Какой фреймворк лучший для начала изучения?");
    driver.findElement(By.cssSelector(".is-empty")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ProseMirror"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Очень интересно как считают работающие люди, какой фреймворк лучше всего начать изучать фронтендеру</p>'}", element);
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ProseMirror"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Очень интересно как считают работающие люди, какой фреймворк лучше всего начать изучать фронтендеру?</p>'}", element);
    }
    driver.findElement(By.id("poll_option")).click();
    driver.findElement(By.id("poll_option")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("poll_option")).sendKeys("React");
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".v1K5c #poll_option"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).sendKeys("Angular");
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".v1K5c #poll_option"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".v1K5c #poll_option"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).sendKeys("Vue");
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".v1K5c #poll_option"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".v1K5c #poll_option"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".v1K5c #poll_option"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".v1K5c #poll_option"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".v1K5c #poll_option")).sendKeys("Что-то другое");
    driver.findElement(By.cssSelector(".Z6xu6:nth-child(1) .sZztf")).click();
    driver.findElement(By.cssSelector(".Im7BZ > .Wjnkw")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.close();
  }

  @Test
  public void createQuestion() {
    driver.get("https://otvet.mail.ru/");
    driver.manage().window().setSize(new Dimension(1050, 716));
    driver.findElement(By.cssSelector(".v1K5c #search")).click();
    driver.findElement(By.cssSelector(".v1K5c #search")).sendKeys("Как пользоваться ");
    driver.findElement(By.cssSelector(".v1K5c #search")).sendKeys("Как пользоваться Selenium");
    driver.findElement(By.cssSelector(".v1K5c #search")).sendKeys("Как пользоваться Selenium?");
    driver.findElement(By.cssSelector(".Im7BZ > .Wjnkw")).click();
    driver.findElement(By.cssSelector(".is-empty")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ProseMirror"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Пытаюсь разобраться с фреймворком для автоматического тестирования </p>'}", element);
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ProseMirror"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Пытаюсь разобраться с фреймворком для автоматического тестирования Selenium, </p>'}", element);
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ProseMirror"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Пытаюсь разобраться с фреймворком для автоматического тестирования Selenium, но только учусь</p>'}", element);
    }
    driver.findElement(By.cssSelector(".qUqs6 > .Rk4Ak span")).click();
    js.executeScript("window.scrollTo(0,307)");
    driver.findElement(By.cssSelector(".UarGH:nth-child(17) .lITgf")).click();
    driver.findElement(By.cssSelector(".vk0M2 > span")).click();
    js.executeScript("window.scrollTo(0,307)");
    driver.findElement(By.cssSelector(".UarGH:nth-child(15) .lITgf")).click();
    driver.findElement(By.cssSelector(".Z6xu6:nth-child(1) svg")).click();
    driver.findElement(By.cssSelector(".Z6xu6:nth-child(1) svg")).click();
    driver.findElement(By.cssSelector(".Z6xu6:nth-child(2) path")).click();
    driver.findElement(By.cssSelector(".Z6xu6:nth-child(2) path")).click();
    driver.findElement(By.cssSelector(".Im7BZ > .Wjnkw")).click();
    driver.close();
  }
  @Test
  public void searchQuestion() {
    driver.get("https://otvet.mail.ru/");
    driver.manage().window().setSize(new Dimension(1050, 716));
    driver.findElement(By.id("search")).click();
    driver.findElement(By.id("search")).sendKeys("тортик");
    driver.findElement(By.cssSelector(".URFp3 > path")).click();
    driver.findElement(By.cssSelector(".MoGUT")).click();
    driver.findElement(By.cssSelector(".T7qE5:nth-child(1) span")).click();
    driver.findElement(By.cssSelector(".UarGH:nth-child(8) .lITgf")).click();
    driver.findElement(By.cssSelector(".T7qE5:nth-child(2) span")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".UarGH:nth-child(12) .lITgf")).click();
    driver.findElement(By.cssSelector(".T7qE5:nth-child(3) span")).click();
    driver.findElement(By.cssSelector(".UarGH:nth-child(6) .lITgf")).click();
    driver.findElement(By.cssSelector(".T7qE5:nth-child(4) span")).click();
    driver.findElement(By.cssSelector(".UarGH:nth-child(2) .lITgf")).click();
    driver.findElement(By.cssSelector(".EyqCX > .Wjnkw")).click();
  }

  @Test
  public void searchOnVoting() {
    driver.get("https://otvet.mail.ru/");
    driver.manage().window().setSize(new Dimension(1050, 716));
    driver.findElement(By.cssSelector(".I9ZMF:nth-child(2) > .tWvjN")).click();
    driver.findElement(By.linkText("Стоит ли смотреть Venom 2 или нет?")).click();
  }

  @Test
  public void searchLiders() {
    driver.get("https://otvet.mail.ru/");
    driver.manage().window().setSize(new Dimension(1050, 716));
    driver.findElement(By.linkText("Лидеры")).click();
    driver.findElement(By.cssSelector(".O8aJU:nth-child(1) span")).click();
    driver.findElement(By.cssSelector(".UarGH:nth-child(2) .lITgf")).click();
    driver.findElement(By.cssSelector(".O8aJU:nth-child(3) span")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".UarGH:nth-child(18) .lITgf")).click();
    driver.findElement(By.cssSelector(".O8aJU:nth-child(2) span")).click();
    driver.findElement(By.cssSelector(".UarGH:nth-child(2) .lITgf")).click();
    driver.findElement(By.cssSelector(".O8aJU:nth-child(4) span")).click();
    driver.findElement(By.cssSelector(".UarGH:nth-child(6) .lITgf")).click();
  }

  @Test
  public void searchFromOpen() {
    driver.get("https://otvet.mail.ru/");
    driver.manage().window().setSize(new Dimension(1050, 716));
    driver.findElement(By.cssSelector(".OefK7 > .tWvjN")).click();
    driver.findElement(By.linkText("Помогите срочно убрать винлокер")).click();
    js.executeScript("window.scrollTo(0,0)");
  }

  @Test
  public void searchFromBest() {
    driver.get("https://otvet.mail.ru/");
    driver.manage().window().setSize(new Dimension(1050, 716));
    driver.findElement(By.cssSelector(".I9ZMF:nth-child(3) > .tWvjN")).click();
    driver.findElement(By.linkText("Почему не работает тик ток?")).click();
    driver.close();
  }

  @Test
  public void registerComapny() {
    driver.get("https://otvet.mail.ru/");
    driver.manage().window().setSize(new Dimension(1050, 716));
    driver.findElement(By.linkText("Для бизнеса")).click();
    driver.findElement(By.cssSelector(".uAWOa > .Wjnkw")).click();
    driver.findElement(By.id("company_name")).click();
    driver.findElement(By.id("company_name")).sendKeys("TestHokure");
    driver.findElement(By.id("company_email")).click();
    driver.findElement(By.id("company_email")).sendKeys("hokure.04@gmail.com");
    driver.findElement(By.id("company_site")).click();
    driver.findElement(By.id("company_site")).sendKeys("https://shatc.ru/");
    driver.findElement(By.id("company_url")).click();
    driver.findElement(By.id("company_url")).sendKeys("Software-lab3");
    driver.findElement(By.cssSelector(".QnEUz")).click();
    driver.findElement(By.id("company_url")).click();
    driver.findElement(By.id("company_url")).sendKeys("SoftwareLab3");
    driver.findElement(By.cssSelector(".QnEUz")).click();
    driver.findElement(By.id("company_url")).click();
    driver.findElement(By.id("company_url")).click();
    driver.findElement(By.cssSelector(".fkTNx > .Wjnkw")).click();
    driver.close();
  }
}
