// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
public class SearchLeadersTest {

  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
    driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(7));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void searchLeadersTest() {
    driver.get("https://otvet.mail.ru/");
    driver.manage().window().setSize(new Dimension(694, 780));
    driver.findElement(By.xpath("//a[contains(text(),\'Лидеры\')]")).click();
    js.executeScript("window.scrollTo(0,0)");
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'82430998\']/a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//label/div/div/div/div/span")).click();
    driver.findElement(By.xpath("//span[contains(.,\'За месяц\')]")).click();
    driver.findElement(By.xpath("//div[3]/label/div/div/div/div/span")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.xpath("//span[contains(.,\'Программирование\')]")).click();
    driver.findElement(By.xpath("//div[2]/label/div/div/div/div/span")).click();
    driver.findElement(By.xpath("//span[contains(.,\'По количеству ответов\')]")).click();
    driver.findElement(By.xpath("//div[4]/label/div/div/div/div/span")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.xpath("//span[contains(.,\'Верстка, CSS, HTML, SVG\')]")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'153634\']/a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.close();
  }
}
