// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

public class SearchQuestionTest {

  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
    driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(7));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void searchQuestionTest() {
    driver.get("https://otvet.mail.ru/");
    driver.manage().window().setSize(new Dimension(1050, 716));

    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
    WebElement searchBox = driver.findElement(By.xpath("//input[@id='search']"));

    searchBox.click();
    searchBox.sendKeys("тортик");

    WebElement suggestion = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//div[6]/div/div/div")));
    suggestion.click();

    driver.findElement(By.xpath("//label/div/div/div/div/span")).click();
    driver.findElement(By.xpath("//div[8]/div/span")).click();
    driver.findElement(By.xpath("//div[2]/label/div/div/div/div")).click();
    driver.findElement(By.xpath("//div[12]/div/span")).click();
    driver.findElement(By.xpath("//div[3]/span")).click();
    driver.findElement(By.xpath("//div[3]/label/div/div/div/div/span")).click();
    driver.findElement(By.xpath("//div[6]/div/span")).click();
    driver.findElement(By.xpath("//div[4]/label/div/div/div/div/span")).click();
    driver.findElement(By.xpath("//div[2]/div[2]/div/span")).click();
    driver.findElement(By.xpath("//div[2]/div/a/div")).click();
    driver.findElement(By.xpath("//b[2]")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.quit();
  }

}
