// Generated by Selenium IDE

import org.junit.jupiter.api.*;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import pages.AskPage;
import pages.HomePage;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class CreatePollTest {
  private static Utils utils;
  private static WebDriver driver;
  private static WebDriverWait wait;
  private static JavascriptExecutor js;
  private static HomePage homePage;
  private static AskPage askPage;

  @BeforeAll
  public static void setUp() {
    utils = new Utils();
    utils.setupDriver();
    driver = utils.getDriver();
    wait = utils.getWaitTime();
    js = utils.getJsExecutor();

    homePage = new HomePage(driver);
    askPage = new AskPage(driver);
  }

  @AfterAll
  public static void tearDown() {
    if(utils != null){
      utils.quitDriver();
    }
  }

  @Test
  @Order(1)
  public void authUser(){
    homePage.clickEnterButton();
    wait.until(ExpectedConditions.frameToBeAvailableAndSwitchToIt(0));
    homePage.enterLoginAndChooseMailType("test_sftware_lab3");
    homePage.enterNumbersAndCode("7", "9");
    WebElement codeField = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//input[@name='Code']")));
    wait.until(driver -> codeField.getAttribute("value").length() == 8);
    System.out.println("Код введен: " + codeField.getAttribute("value"));
    homePage.submitLogin();
  }

  @Test
  @Order(2)
  public void createPollTest() {
    homePage.clickAskButton();
    askPage.createPoll();
  }
}
